<a href="https://colab.research.google.com/github/fonslucens/test_deeplearning/blob/master/diff_sigmoid_softmax.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# sigmoid

In [1]:
import tensorflow as tf

In [6]:
a = tf.constant([4.0, 1.0, 3.0 ], dtype = tf.float32)
a, type(a)

(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([4., 1., 3.], dtype=float32)>,
 tensorflow.python.framework.ops.EagerTensor)

In [7]:
b = tf.keras.activations.sigmoid(a)
b

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.98201376, 0.7310586 , 0.95257413], dtype=float32)>

In [8]:
b.numpy()

array([0.98201376, 0.7310586 , 0.95257413], dtype=float32)

# softmax

In [9]:
inputs = tf.random.normal(shape=(1, 3))
inputs

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[ 1.5138141 , -0.9445081 ,  0.04308564]], dtype=float32)>

In [10]:
outputs = tf.keras.activations.softmax(inputs)
outputs

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.7602618 , 0.06506201, 0.17467628]], dtype=float32)>

In [11]:
outputs.numpy()

array([[0.7602618 , 0.06506201, 0.17467628]], dtype=float32)