<a href="https://colab.research.google.com/github/fonslucens/test_deeplearning/blob/master/iris_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn import datasets

In [3]:
iris = datasets.load_iris()
iris

{'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ===========

In [4]:
import pandas as pd
df_iris = pd.DataFrame(iris.data)
df_iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       150 non-null    float64
 1   1       150 non-null    float64
 2   2       150 non-null    float64
 3   3       150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB


In [5]:
import sqlite3
connect = sqlite3.connect('./db.sqlite3')
df_iris.to_sql('iris_resource', connect, if_exists='append', index=False)

In [7]:
df_load = pd.read_sql_query('select * from iris_resource', connect)
df_load.head(4)

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2

In [8]:
x_data = df_load.to_numpy()
x_data.shape

(150, 4)

In [12]:
import numpy as np

In [13]:
y_data = iris.target
y_data, np.unique(y_data)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 array([0, 1, 2]))

In [10]:
import tensorflow as tf

In [16]:
model = tf.keras.Sequential()

model.add(tf.keras.Input(shape=(4,)))   # input layer

model.add(tf.keras.layers.Dense(64,activation='relu'))   # hidden layer
model.add(tf.keras.layers.Dense(24,activation='relu'))   # hidden layer

model.add(tf.keras.layers.Dense(3, activation='softmax'))   # output layer

model.compile(optimizer='adam', loss='mse', metrics=['acc'])   # gadget

In [15]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 64)                320       
_________________________________________________________________
dense_1 (Dense)              (None, 24)                1560      
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 75        
Total params: 1,955
Trainable params: 1,955
Non-trainable params: 0
_________________________________________________________________


In [17]:
model.fit(x_data, y_data, epochs=50, validation_split=0.3) # 학습

Epoch 1/50
4/4 [==============================] - 1s 76ms/step - loss: 0.4191 - acc: 0.0476 - val_loss: 2.7895 - val_acc: 0.1111
Epoch 2/50
4/4 [==============================] - 0s 11ms/step - loss: 0.4014 - acc: 0.0667 - val_loss: 2.7796 - val_acc: 0.0000e+00
Epoch 3/50
4/4 [==============================] - 0s 12ms/step - loss: 0.3976 - acc: 0.2286 - val_loss: 2.7808 - val_acc: 0.0000e+00
Epoch 4/50
4/4 [==============================] - 0s 12ms/step - loss: 0.3998 - acc: 0.4762 - val_loss: 2.7812 - val_acc: 0.0000e+00
Epoch 5/50
4/4 [==============================] - 0s 13ms/step - loss: 0.3989 - acc: 0.4762 - val_loss: 2.7792 - val_acc: 0.0000e+00
Epoch 6/50
4/4 [==============================] - 0s 12ms/step - loss: 0.3974 - acc: 0.3810 - val_loss: 2.7792 - val_acc: 0.0000e+00
Epoch 7/50
4/4 [==============================] - 0s 11ms/step - loss: 0.3973 - acc: 0.4190 - val_loss: 2.7788 - val_acc: 0.0000e+00
Epoch 8/50
4/4 [==============================] - 0s 12ms/step - loss: 0.

# Evaluation

In [18]:
model.evaluate(x_data, y_data)

5/5 [==============================] - 0s 2ms/step - loss: 1.1111 - acc: 0.3267


[1.1111431121826172, 0.3266666531562805]

# service

In [20]:
x_data[25], y_data[25]

(array([5. , 3. , 1.6, 0.2]), 0)

In [23]:
pred = model.predict([[5. , 3. , 1.6, 0.2]])
pred

array([[0.33218807, 0.33516437, 0.3326476 ]], dtype=float32)

In [24]:
import numpy as np
np.argmax(pred)

1