<a href="https://colab.research.google.com/github/fonslucens/test_deeplearning/blob/master/NaverSentimentAnalysis_loadmodel_LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
loaded_model = tf.keras.models.load_model('./NaverSentimentAnalysis_LSTM.h5')
loaded_model

In [3]:
!python -m pip install konlpy

     |████████████████████████████████| 19.4 MB 1.3 MB/s 
     |████████████████████████████████| 86 kB 5.6 MB/s 
     |████████████████████████████████| 448 kB 57.9 MB/s 
  Attempting uninstall: beautifulsoup4
    Found existing installation: beautifulsoup4 4.6.3
    Uninstalling beautifulsoup4-4.6.3:
      Successfully uninstalled beautifulsoup4-4.6.3


In [4]:
import konlpy

In [ ]:
words = list()
for tok in temp_x:
  if tok not in stopwords:
    words.append(tok)


In [5]:
import pickle

In [9]:
stopwords = pickle.load(open('./stopwords.pkl','rb'))
print(stopwords)

['의', '가', '이', '은', '들', '는', '좀', '잘', '걍', '과', '도', '를', '으로', '자', '에', '와', '한', '하다']


In [10]:
# 감독이 예술이네.  --> 웹 사용자가 입력.
okt = konlpy.tag.Okt()
new_sentence = okt.morphs('감독이 예술이네.', stem=True)
new_sentence = [ tok for tok in new_sentence if tok not in stopwords ]
new_sentence

['감독', '예술', '이네', '.']

In [11]:
tokenizer = pickle.load(open('./tokenizer.pkl', 'rb'))
tokenizer

In [22]:
encoded = tokenizer.texts_to_sequences([new_sentence])
encoded
pad_new = tf.keras.preprocessing.sequence.pad_sequences(encoded, maxlen=50)
pad_new

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,  92, 128,   1]],
      dtype=int32)

In [18]:
score = loaded_model.predict(pad_new)
score

array([[0.50163543]], dtype=float32)

In [20]:
if(score > 0.5):
  print('긍정', score*100)
else :
  print('부정', score*100)

긍정 [[50.163544]]


In [ ]:
okt = konlpy.tag.Okt()
new_sentence = okt.morphs('이 영화 꽝이네.', stem=True)
new_sentence = [ tok for tok in new_sentence if tok not in stopwords ]
encoded = tokenizer.texts_to_sequences([new_sentence])
pad_new = tf.keras.preprocessing.sequence.pad_sequences(encoded, maxlen=50)
score = loaded_model.predict(pad_new)

In [28]:
def sentiment_predict(sentence):
  okt = konlpy.tag.Okt()
  new_sentence = okt.morphs(sentence, stem=True)
  new_sentence = [ tok for tok in new_sentence if tok not in stopwords ]
  encoded = tokenizer.texts_to_sequences([new_sentence])
  pad_new = tf.keras.preprocessing.sequence.pad_sequences(encoded, maxlen=50)
  score = loaded_model.predict(pad_new)
  return score

In [29]:
words = '이 영화 꽝이네.'
sentiment_predict(words)

array([[0.5020227]], dtype=float32)

In [30]:
words = '영화가 좋으니 마음도 좋네요.'
sentiment_predict(words)

array([[0.5060966]], dtype=float32)