<a href="https://colab.research.google.com/github/fonslucens/test_deeplearning/blob/master/Notescale_LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
note_seq = ['g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'd8', 'e8', 'f8', 'g8', 'g8', 'g4',
       'g8', 'e8', 'e8', 'e8', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4',
       'd8', 'd8', 'd8', 'd8', 'd8', 'e8', 'f4', 'e8', 'e8', 'e8', 'e8', 'e8', 'f8', 'g4',
       'g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4']

In [2]:
note_seq[0:4], note_seq[1:5], note_seq[2:6]

(['g8', 'e8', 'e4', 'f8'], ['e8', 'e4', 'f8', 'd8'], ['e4', 'f8', 'd8', 'd4'])

In [3]:
code2idx = {'c4':0, 'd4':1, 'e4':2, 'f4':3, 'g4':4, 'a4':5, 'b4':6,
            'c8':7, 'd8':8, 'e8':9, 'f8':10, 'g8':11, 'a8':12, 'b8':13}

In [4]:
len(note_seq), range(len(note_seq)-4) # [4,8,12,....]

(54, range(0, 50))

In [5]:
code2idx['g8']

11

In [6]:
dataset = list()
for i in range(len(note_seq)-4) : 
  subset = note_seq[i:i+4]
  items = list()
  # print(subset)
  for item in subset:
    # print(code2idx[item])
    items.append(code2idx[item])
  # print(items)
  dataset.append(items)

print(dataset)

[[11, 9, 2, 10], [9, 2, 10, 8], [2, 10, 8, 1], [10, 8, 1, 7], [8, 1, 7, 8], [1, 7, 8, 9], [7, 8, 9, 10], [8, 9, 10, 11], [9, 10, 11, 11], [10, 11, 11, 4], [11, 11, 4, 11], [11, 4, 11, 9], [4, 11, 9, 9], [11, 9, 9, 9], [9, 9, 9, 10], [9, 9, 10, 8], [9, 10, 8, 1], [10, 8, 1, 7], [8, 1, 7, 9], [1, 7, 9, 11], [7, 9, 11, 11], [9, 11, 11, 9], [11, 11, 9, 9], [11, 9, 9, 2], [9, 9, 2, 8], [9, 2, 8, 8], [2, 8, 8, 8], [8, 8, 8, 8], [8, 8, 8, 8], [8, 8, 8, 9], [8, 8, 9, 3], [8, 9, 3, 9], [9, 3, 9, 9], [3, 9, 9, 9], [9, 9, 9, 9], [9, 9, 9, 9], [9, 9, 9, 10], [9, 9, 10, 4], [9, 10, 4, 11], [10, 4, 11, 9], [4, 11, 9, 2], [11, 9, 2, 10], [9, 2, 10, 8], [2, 10, 8, 1], [10, 8, 1, 7], [8, 1, 7, 9], [1, 7, 9, 11], [7, 9, 11, 11], [9, 11, 11, 9], [11, 11, 9, 9]]


In [7]:
import numpy as np
datasets = np.array(dataset)

In [8]:
x_train = datasets[:,0:3]
x_train.shape #x_train

(50, 3)

In [9]:
y_train = datasets[:,3]
y_train.shape #y_train

(50,)

In [10]:
len(code2idx)

14

In [11]:
x_train  = x_train /13  #len(code2idx)
x_train[3]

array([0.76923077, 0.61538462, 0.07692308])

# make model

In [12]:
import tensorflow as tf

In [17]:
x_train.shape, x_train[2] # --> tensorfloq type(tensor) (50, 3, 1), --> metrix

((50, 3), array([0.15384615, 0.76923077, 0.61538462]))

In [18]:
X_train = np.reshape(x_train, (50, 3, 1)) #tensor
X_train.shape, X_train[2]

((50, 3, 1), array([[0.15384615],
        [0.76923077],
        [0.61538462]]))

In [23]:
model = tf.keras.models.Sequential()

model.add(tf.keras.Input(shape=(3,1))) # input layer
model.add(tf.keras.layers.LSTM(128)) #hidden layer 
model.add(tf.keras.layers.Dense(13, activation='softmax')) # output layer

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy']) #gadget

In [34]:
hist = model.fit(X_train, y_train, epochs=500, batch_size=10)  # 50 / 5 = 10

Epoch 1/500
5/5 [==============================] - 0s 5ms/step - loss: 0.7930 - accuracy: 0.6800
Epoch 2/500
5/5 [==============================] - 0s 5ms/step - loss: 0.7931 - accuracy: 0.6800
Epoch 3/500
5/5 [==============================] - 0s 5ms/step - loss: 0.7833 - accuracy: 0.6600
Epoch 4/500
5/5 [==============================] - 0s 5ms/step - loss: 0.7783 - accuracy: 0.6800
Epoch 5/500
5/5 [==============================] - 0s 5ms/step - loss: 0.7956 - accuracy: 0.6600
Epoch 6/500
5/5 [==============================] - 0s 6ms/step - loss: 0.7819 - accuracy: 0.6600
Epoch 7/500
5/5 [==============================] - 0s 5ms/step - loss: 0.7834 - accuracy: 0.6400
Epoch 8/500
5/5 [==============================] - 0s 5ms/step - loss: 0.7749 - accuracy: 0.7000
Epoch 9/500
5/5 [==============================] - 0s 6ms/step - loss: 0.7794 - accuracy: 0.7000
Epoch 10/500
5/5 [==============================] - 0s 6ms/step - loss: 0.8006 - accuracy: 0.6600
Epoch 11/500
5/5 [===========

In [25]:
model.evaluate(X_train, y_train)

2/2 [==============================] - 0s 9ms/step - loss: 2.4822 - accuracy: 0.3400


[2.4822003841400146, 0.3400000035762787]

In [27]:
X_train[4:5]

array([[[0.61538462],
        [0.07692308],
        [0.53846154]]])

In [37]:
model.predict(X_train[4:5])

array([[2.4689932e-08, 7.0719524e-12, 9.2872951e-06, 5.2600529e-04,
        8.0879897e-07, 1.1744355e-08, 3.0277519e-08, 2.9209603e-05,
        4.0145326e-01, 5.9767890e-01, 3.0250812e-04, 1.7255264e-08,
        3.2369794e-08]], dtype=float32)

In [28]:
first = 0.61538462
second = 0.07692308
third = 0.53846154

In [29]:
pred = model.predict([[[first], [second], [third]]])

In [38]:
model.predict(X_train[0:1])

array([[3.1393392e-07, 4.5634186e-04, 2.2331538e-02, 1.5414051e-05,
        7.2888390e-05, 3.4985871e-07, 1.5126312e-07, 1.1565816e-03,
        5.2222945e-03, 5.3228214e-02, 9.1119796e-01, 6.3177869e-03,
        2.3297304e-07]], dtype=float32)

In [30]:
np.argmax(pred)

9

In [31]:
code2idx = {'c4':0, 'd4':1, 'e4':2, 'f4':3, 'g4':4, 'a4':5, 'b4':6,
            'c8':7, 'd8':8, 'e8':9, 'f8':10, 'g8':11, 'a8':12, 'b8':13}

In [ ]:
note_seq = ['g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'd8', 'e8', 'f8', 'g8', 'g8', 'g4',
       'g8', 'e8', 'e8', 'e8', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4',
       'd8', 'd8', 'd8', 'd8', 'd8', 'e8', 'f4', 'e8', 'e8', 'e8', 'e8', 'e8', 'f8', 'g4',
       'g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4']